# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ari's Corner of the Web
email: ariellamiller99@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Ari, a young woman in Kansas City who is passionate about technology. 
  My early interests in art and design evolved into embracing programming as my authentic art form. 
  Overcoming imposter syndrome in the male-dominated STEM field, my self-learning and determination culminated in pursuing a computer science degree. 
  Beyond academia, I champion inclusivity as my goal is to inspire other women looking for their place in STEM fields. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ariellam99.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ariellam99

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate-v2

# Include
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Formatting
defaults:
  # _posts
  - scope:
      path: ""
      type: _posts
  - values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
      show_date: true
  #_pages
  - scope:
        path: ""
        type: _pages
    values:
        author_profile: true

# Pagination
paginate: 5 # posts per page
paginate_path: /blog/page:num/

# Site Author Profile
author:
  name: "Ariella Miller"
  avatar: "assets/images/FullSizeRender.jpeg"
  bio: "Computer Science Student & Steminist"
  location: "Kansas City, MO"
  email: ariellamiller99@gmail.com
  facebook:
  github: "ariellam99"
  instagram: "ari_m_dev"
  linkedin: "ariella-miller-dev"
  twitter:
  youtube: "ari-m-dev"

# Site Footer
footer:
  links:
    - label:
        icon: "fa-brands fa-linkedin"
        url: "www.linkedin.com/in/ariella-miller-dev"
    - label:
        icon: "fa-brands fa-github"
        url: "https://github.com/ariellam99"
    - label:
        icon: "fa-brands fa-instagram"
        url: "https://www.instagram.com/ari_m_dev/"
    - label:
        icon: "fa-brands fa-youtube"
        url: "https://www.youtube.com/@ari-m-dev"

# Archives
category_archives:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  archives:
    output: true
    permalink: /archives/:path/